version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-payment
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 140610
      POSTGRES_DB: payment_system
      POSTGRES_INITDB_ARGS: "-E UTF8"
      TZ: America/Sao_Paulo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d payment_system"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - payment_network

volumes:
  postgres_data:
    driver: local

networks:
  payment_network:
    driver: bridge

